function [xout,yout,Wout,Hout,rho]=Meanshift_tracker(xin,yin,Widin,HeiIn,I,TargetModel)
    Delta_h=0.1;
    Gamma=0.5;
     xin1=floor(xin);
     yin1=floor(yin);  
    if(xin1<1)
        xin1=1;
    end
    if(xin1>size(I,2)) 
        xin1=size(I,2);
    end 
    if(yin1<1)
        yin1=1;
    end
    if(yin1>size(I,1)) 
        yin1=size(I,1);
    end    
    
    Win1=Widin;
    Hin1=HeiIn;
    if(Win1<=0)
        Win1=1;
    end
    if(Hin1<=0)
        Hin1=1;
    end
    if(Win1>=size(I,2)/3) 
        Win1=size(I,2)/3;
    end
    if(Hin1>=size(I,1)/3)
        Hin1=size(I,1)/3;
    end        
    W1=round(Win1*(1-Delta_h)+0.5);
    H1=round(Hin1*(1-Delta_h)+0.5);
    [xin1,yin1,xo1,yo1,rho1]=mean_shift_iter(xin1,yin1,W1,H1,I,TargetModel);
    Wout=Win1;
    Hout=Hin1;
    [xin1,yin1,xout,yout,rho]=mean_shift_iter(xin1,yin1,Wout,Hout,I,TargetModel);
    W3=floor(Win1*(1+Delta_h)+0.5);
    H3=floor(Hin1*(1+Delta_h)+0.5);
    [xin1,yin1,xo3,yo3,rho3]=mean_shift_iter(xin1,yin1,W3,H3,I,TargetModel);
    if(rho<rho1)
        rho=rho1;
        xout=(xo1+xout)/2;
        yout=(yo1+yout)/2;
        Wout=W1;
        Hout=H1;
    end
    if(rho<rho3)
        rho=rho3;
        xout=xo3;
        yout=yo3;
        Wout=W3;
        Hout=H3;
    end
    Wout=floor(Gamma*Wout+(1-Gamma)*Widin+0.5);
    Hout=floor(Gamma*Hout+(1-Gamma)*HeiIn+0.5);

end